### ISSUE TITLE
Consider simplifying type definitions of React components

### ISSUE THREAD

**Issue by mlodato517** [LowLevelAcademy/LowLevelAcademy#1]
This is a super preference-based style thing so feel free to ignore it! I figured I'd bring it up in case you were interested and I'd gladly make a PR for it if you do want the changes.

The type definitions for the components are a little verbose and I think we could simplify them a bit. Take for example [Page](https://github.com/LowLevelAcademy/LowLevelAcademy/blob/master/components/Page.tsx):
```js
import React, { PropsWithChildren } from "react";

export interface PageProps { ...}

const Page: React.FunctionComponent<PropsWithChildren<PageProps>> = (
  props: PropsWithChildren<PageProps>
) => {
```

Using `FunctionComponent` is great and, because of its greatness, you actually don't need to specify `PropsWithChildren` here! The definition for `FunctionComponent` is:
```js
    interface FunctionComponent<P = {}> {
        (props: PropsWithChildren<P>, context?: any): ReactElement<any, any> | null;
        ...
    }
```
so it already wraps the type `P` you give it in `PropsWithChildren`! So we can simplify this to:
```js
import React, { PropsWithChildren } from "react";

export interface PageProps { ...}

const Page: React.FunctionComponent<PageProps> = (
  props: PropsWithChildren<PageProps>
) => {
```

Next, because we've said that `Page` is a `React.FunctionComponent<PageProps>`, Typescript knows that the type of `props` must be `PropsWithChildren<PageProps>`! So we can simplify this to:
```js
import React from "react";

export interface PageProps { ...}

const Page: React.FunctionComponent<PageProps> = (props) => {
```

A super small change we could make is that React has a type alias `FC` for `FunctionComponent` that we could import from `React`:
```js
import React, { FC } from "react";

export interface PageProps { ...}

const Page: FC<PageProps> = (props) => {
```

Finally, and this is also super preference-based, we could destructure `props` to either:
```js
const Page: FC<PageProps> = ({ children, isCurrent, title }) => {
```
or
```js
const Page: FC<PageProps> = ({ children, ...otherProps }) => {
```
for better copy-pasting between files.

Lemme know if you're interested in any of these changes and I'd be glad to incorporate them!

**Comment by nbaksalyar** [comment]
These are excellent suggestions, thank you! I think some of them can be done largely with find & replace.

> Lemme know if you're interested in any of these changes

Definitely - I'll be publishing a new batch of changes soon, and I can also include your suggestions - unless you would prefer to contribute. :)

**Comment by mlodato517** [comment]
I would love to contribute :-)

**Comment by nbaksalyar** [comment]
> I'll be publishing a new batch of changes soon

Now the pull request #2 should include everything.

Please let me know if you will need any help with this!

**Comment by mlodato517** [comment]
Did a quick first pass in https://github.com/LowLevelAcademy/LowLevelAcademy/pull/3
