### ISSUE TITLE
UtfPlayground does not apply the selected base when encoding view string

### ISSUE THREAD

**Issue by clemensw** [LowLevelAcademy/LowLevelAcademy#13]
https://lowlvl.org/prerequisites/binary-and-hexadecimal-numbers concludes with "let’s use hexadecimal encoding", but the displayed values are decimal. It looks as if the display does not take into account the selected encoding. I suggest #12 as a possible fix.

**Comment by nbaksalyar** [comment]
Closed by #12. Thank you!
